//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Business.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTEntities : DbContext
    {
        public MTEntities()
            : base("name=MTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_BaseInfo> T_BaseInfo { get; set; }
        public DbSet<T_Role> T_Role { get; set; }
        public DbSet<T_User> T_User { get; set; }
        public DbSet<T_UserRole> T_UserRole { get; set; }
        public DbSet<T_Log> T_Log { get; set; }
        public DbSet<T_DataItem> T_DataItem { get; set; }
        public DbSet<T_DataItemDetail> T_DataItemDetail { get; set; }
        public DbSet<T_Department> T_Department { get; set; }
        public DbSet<T_Menu> T_Menu { get; set; }
        public DbSet<T_RoleMenu> T_RoleMenu { get; set; }
    }
}
