//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 基础信息表
    /// </summary>
    public partial class T_BaseInfo
    {
    	/// <summary>
    	/// GUID主键
    	/// </summary>
        public System.Guid F_ID { get; set; }
    	/// <summary>
    	/// 目录编码
    	/// </summary>
        public string F_CatalogCode { get; set; }
    	/// <summary>
    	/// 目录名称
    	/// </summary>
        public string F_CatalogName { get; set; }
    	/// <summary>
    	/// 项目编码
    	/// </summary>
        public string F_ItemCode { get; set; }
    	/// <summary>
    	/// 项目名称
    	/// </summary>
        public string F_ItemName { get; set; }
    	/// <summary>
    	/// 项目排序序号
    	/// </summary>
        public Nullable<int> F_ItemSort { get; set; }
    	/// <summary>
    	/// 创建者UserID
    	/// </summary>
        public Nullable<System.Guid> F_CreateUserID { get; set; }
    	/// <summary>
    	/// 创建者姓名
    	/// </summary>
        public string F_CreateUserName { get; set; }
    	/// <summary>
    	/// 创建时间
    	/// </summary>
        public Nullable<System.DateTime> F_CreateTime { get; set; }
    	/// <summary>
    	/// 修改人UserID
    	/// </summary>
        public Nullable<System.Guid> F_ModifyUserID { get; set; }
    	/// <summary>
    	/// 修改人姓名
    	/// </summary>
        public string F_ModifyUserName { get; set; }
    	/// <summary>
    	/// 修改时间
    	/// </summary>
        public Nullable<System.DateTime> F_ModifyTime { get; set; }
    	/// <summary>
    	/// 是否有效(0删除1有效)
    	/// </summary>
        public Nullable<int> F_isValid { get; set; }
    }
}
