//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 
    /// </summary>
    public partial class T_Department
    {
    	/// <summary>
    	/// 主键
    	/// </summary>
        public System.Guid F_ID { get; set; }
    	/// <summary>
    	/// 完整名称
    	/// </summary>
        public string F_FullName { get; set; }
    	/// <summary>
    	/// 短名称
    	/// </summary>
        public string F_ShortName { get; set; }
    	/// <summary>
    	/// 助记码
    	/// </summary>
        public string F_HelpCode { get; set; }
    	/// <summary>
    	/// 父级部门编码
    	/// </summary>
        public Nullable<System.Guid> F_ParentID { get; set; }
    	/// <summary>
    	/// 父级部门名称
    	/// </summary>
        public string F_ParentName { get; set; }
    	/// <summary>
    	/// 级别
    	/// </summary>
        public Nullable<int> F_Level { get; set; }
    	/// <summary>
    	/// 排序
    	/// </summary>
        public Nullable<int> F_Sort { get; set; }
    	/// <summary>
    	/// 是否启用
    	/// </summary>
        public Nullable<int> F_isEnable { get; set; }
    	/// <summary>
    	/// 录入人编码
    	/// </summary>
        public Nullable<System.Guid> F_AddUserID { get; set; }
    	/// <summary>
    	/// 录入人姓名
    	/// </summary>
        public string F_AddUserName { get; set; }
    	/// <summary>
    	/// 录入时间
    	/// </summary>
        public Nullable<System.DateTime> F_AddTime { get; set; }
    	/// <summary>
    	/// 修改人编码
    	/// </summary>
        public Nullable<System.Guid> F_UpdateUserID { get; set; }
    	/// <summary>
    	/// 修改人姓名
    	/// </summary>
        public string F_UpdateUserName { get; set; }
    	/// <summary>
    	/// 修改时间
    	/// </summary>
        public Nullable<System.DateTime> F_UpdateTime { get; set; }
    	/// <summary>
    	/// 数据状态(0删除1正常)
    	/// </summary>
        public Nullable<int> F_isValid { get; set; }
    	/// <summary>
    	/// 备注
    	/// </summary>
        public string F_Remark { get; set; }
    }
}
