//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 日志表
    /// </summary>
    public partial class T_Log
    {
    	/// <summary>
    	/// GUID主键
    	/// </summary>
        public System.Guid F_ID { get; set; }
    	/// <summary>
    	/// Controller控制器名称
    	/// </summary>
        public string F_ControllerName { get; set; }
    	/// <summary>
    	/// Action方法名称
    	/// </summary>
        public string F_ActionName { get; set; }
    	/// <summary>
    	/// 日志标题
    	/// </summary>
        public string F_Title { get; set; }
    	/// <summary>
    	/// 日志内容
    	/// </summary>
        public string F_Content { get; set; }
    	/// <summary>
    	/// 日志类型编码
    	/// </summary>
        public string F_LogType { get; set; }
    	/// <summary>
    	/// 日志类型名称
    	/// </summary>
        public string F_LogTypeName { get; set; }
    	/// <summary>
    	/// 记录时间
    	/// </summary>
        public Nullable<System.DateTime> F_WriteTime { get; set; }
    	/// <summary>
    	/// 是否有效(0删除1有效)
    	/// </summary>
        public Nullable<int> F_isValid { get; set; }
    	/// <summary>
    	/// 用户姓名
    	/// </summary>
        public string F_UserName { get; set; }
    	/// <summary>
    	/// 用户登录名
    	/// </summary>
        public string F_LoginName { get; set; }
    }
}
