//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 
    /// </summary>
    public partial class T_Parameter
    {
    	/// <summary>
    	/// 主键
    	/// </summary>
        public System.Guid F_ID { get; set; }
    	/// <summary>
    	/// 目录编码
    	/// </summary>
        public string F_CatalogCode { get; set; }
    	/// <summary>
    	/// 目录名称
    	/// </summary>
        public string F_CatalogName { get; set; }
    	/// <summary>
    	/// 参数编码
    	/// </summary>
        public string F_Code { get; set; }
    	/// <summary>
    	/// 参数名称
    	/// </summary>
        public string F_Name { get; set; }
    	/// <summary>
    	/// 参数值
    	/// </summary>
        public string F_Value { get; set; }
    	/// <summary>
    	/// 参数说明
    	/// </summary>
        public string F_Explain { get; set; }
    	/// <summary>
    	/// 排序
    	/// </summary>
        public Nullable<int> F_Sort { get; set; }
    	/// <summary>
    	/// 录入人编码
    	/// </summary>
        public Nullable<System.Guid> F_AddUserID { get; set; }
    	/// <summary>
    	/// 录入人姓名
    	/// </summary>
        public string F_AddUserName { get; set; }
    	/// <summary>
    	/// 录入时间
    	/// </summary>
        public Nullable<System.DateTime> F_AddTime { get; set; }
    	/// <summary>
    	/// 修改人编码
    	/// </summary>
        public Nullable<System.Guid> F_UpdateUserID { get; set; }
    	/// <summary>
    	/// 修改人姓名
    	/// </summary>
        public string F_UpdateUserName { get; set; }
    	/// <summary>
    	/// 修改时间
    	/// </summary>
        public Nullable<System.DateTime> F_UpdateTime { get; set; }
    	/// <summary>
    	/// 数据状态
    	/// </summary>
        public Nullable<int> F_isValid { get; set; }
    	/// <summary>
    	/// 备注
    	/// </summary>
        public string F_Remark { get; set; }
    }
}
